/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SQS.Message.Queues.Client;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
